name: racs-tools
channels:
- astropy
- conda-forge
- defaults
- pkgw-forge
dependencies:
- python=3.10
- pip
- numpy
- scipy
- astropy
- mpi4py
- pip:
  - spectral_cube
  - radio_beam
  - tqdm
  - ./
