name: racs-tools
channels:
- astropy
- conda-forge
- defaults
- pkgw-forge
dependencies:
- python=3.8
- pip
- numpy
- scipy
- astropy
- gfortran
- mpi4py
- pip:
  - spectral_cube
  - radio_beam
  - schwimmbad
  - tqdm
  - ./