# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-numpy
        python -m pip install --upgrade pip
        python -m pip install pytest numpy
        python -m pip install .
    - name: Install miriad
      run: |
        apt-get update && apt-get install -y     wget     bzip2     libgfortran3     libx11-6     csh
        cd /opt
        wget     ftp://ftp.atnf.csiro.au/pub/software/miriad/miriad-common.tar.bz2     ftp://ftp.atnf.csiro.au/pub/software/miriad/miriad-linux64.tar.bz2 &&     tar xf miriad-common.tar.bz2 &&     tar xf miriad-linux64.tar.bz2 &&     rm -rf *tar.bz2
        cd /opt/miriad
        sed -e "s,@MIRROOT@,/opt/miriad," scripts/MIRRC.sh.in > MIRRC.sh &&     chmod 644 MIRRC.sh &&     echo source /opt/miriad/MIRRC.sh >> /root/.bashrc &&     echo export PATH=\${MIRBIN}:\${PATH} >> /root/.bashrc
        export PATH=/opt/miriad/linux64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: Test with pytest
      run: |
        pytest
